import Head from "next/head";
import { Footer, Header, Main } from "../components";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen px-[100px]">
      <Head>
        <title>Fashion | Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <Main />
      <Footer />
    </div>
  );
}
